const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict'),{JSDOM}=require('jsdom');
const source=fs.readFileSync('cash-finance.js','utf8');
let now='2026-10-05T19:27:08Z';class Clock extends Date{constructor(...args){super(...(args.length?args:[now]));}}
const ctx={window:{},Date:Clock,Intl,Number,Math,String,Set};vm.createContext(ctx);vm.runInContext(source,ctx);const c=ctx.window.ARHITTEKCash;
const state={projects:[{id:'p',price:150000,advance:50000,end_date:'2026-11-15'}],ledger:[],companyIncome:[],companyExpenses:[]};assert.equal(c.balance(state),20000);
state.ledger.push({id:'old',type:'advance',amount:999000,entry_date:'2026-10-01',created_at:'2026-10-01T00:00:00Z'});assert.equal(c.balance(state),20000);
state.ledger.push({id:'new',type:'advance',amount:50000,entry_date:'2026-10-05',created_at:'2026-10-05T19:27:09Z'});assert.equal(c.balance(state),70000);
state.ledger.push({type:'role_payout',amount:100000,entry_date:'2026-10-05',created_at:'2026-10-05T19:28:09Z'});assert.equal(c.balance(state),70000);
state.companyExpenses.push({id:'rent',category:'Аренда',amount:110000,expense_date:'2026-10-05',created_at:'2026-10-05T19:28:09Z'});assert.equal(c.balance(state),-40000);
state.ledger.push({id:'salary',type:'salary_payment',amount:20000,entry_date:'2026-10-05',created_at:'2026-10-05T19:28:09Z'});assert.equal(c.balance(state),-60000);
state.companyIncome.push({id:'lease',amount:20000,income_date:'2026-10-05',created_at:'2026-10-05T19:28:09Z'});assert.equal(c.balance(state),-40000);
state.companyExpenses[0].deleted_at='2026-10-05';assert.equal(c.balance(state),70000);
assert.equal(c.expected(state.projects[0]),100000);assert.equal(c.dueProjects(state,'2026-11').length,1);state.projects[0].end_date='2026-12-15';assert.equal(c.dueProjects(state,'2026-11').length,0);assert.equal(c.dueProjects(state,'2026-12').length,1);
now='2026-10-31T21:00:00Z';assert.equal(c.day(),'2026-11-01');assert.equal(c.monthSummary(state,'2026-10').status,'Закрыт');assert.equal(c.monthSummary(state,'2026-11').opening,c.monthSummary(state,'2026-10').closing);assert.equal(c.shift('2026-12',1),'2027-01');
const dom=new JSDOM('<div id="view-finance"><div id="financeVisualTabs"></div>'+['overview','income','expense','reserve','forecast','team'].map(x=>'<div class="finance-visual-panel" data-fin-panel="'+x+'"></div>').join('')+'</div>',{url:'https://app.test',runScripts:'outside-only'}),w=dom.window;w.setTimeout=fn=>fn();w.setInterval=()=>0;w.session={isAdmin:true};w.state={employees:[],ledger:[],companyIncome:[],companyExpenses:[],projects:[],statuses:[]};w.getCompanyReserveBalance=()=>190000;w.escapeHtml=s=>String(s);w.fmtMoney=n=>String(n)+' ₽';w.fmtDate=s=>s;w.ruMonthLabel=s=>s;w.timesheetMonthRange=m=>({from:m+'-01',to:m+'-30'});w.completedProjectEarningsForRange=()=>({employees:{}});w.splitPayrollByEmployee=()=>({result:{}});w.ledgerTypeLabels={};w.findStatus=()=>({});w.showToast=()=>{};w.loadAll=async()=>{};
let db=[],insertCount=0;w.sb={from:table=>({select:()=>({is:()=>({eq:async()=>({data:db.filter(x=>x.table===table),error:null})})}),insert:async row=>{insertCount++;const r={...row,id:String(insertCount),created_at:new Date().toISOString(),table};db.push(r);w.state[table==='company_income'?'companyIncome':'companyExpenses'].push(r);return {error:null}}})};
w.eval(source);assert(w.document.getElementById('cash-panel-overview').textContent.includes('20000 ₽'));
const buttons=()=>w.document.querySelectorAll('[data-cash-action="confirm"][data-id="sublease"]');assert.equal(buttons().length,1);
(async()=>{buttons()[0].click();buttons()[0].click();await new Promise(r=>setTimeout(r,30));assert.equal(insertCount,1);assert.equal(buttons().length,0);assert.equal(w.getCompanyReserveBalance(),40000);console.log('PASS: 20k snapshot, actual receipt only, no accrual debit, rent/salary/lease cash, deletion, deadline movement, Moscow month rollover and carry, recurring confirmation duplicate click');})();
