(()=>{
window.__writes=[];window.__fail=null;
window.__db={projects:[],employees:[{id:'admin',name:'Мансур',role:'Директор',is_admin:true,active:true,is_salaried:true,fixed_salary:50000,created_at:'2026-01-01T00:00:00Z'},{id:'designer',name:'Амина',role:'Ведущий дизайнер',active:true,is_salaried:true,fixed_salary:50000,created_at:'2026-01-01T00:00:00Z'},{id:'visual',name:'Ислам',role:'Визуализатор',active:true},{id:'architect',name:'Адам',role:'Архитектор',active:true}],categories:[{id:'design',name:'Дизайн интерьера',department_id:'d',fee_percent:0,fee_base:'m2'},{id:'arch',name:'Архитектурное решение',department_id:'d',fee_percent:40,fee_base:'profit'},{id:'land',name:'Ландшафтный дизайн',department_id:'d',fee_percent:40,fee_base:'profit'},{id:'build',name:'Строительство',department_id:'b',fee_percent:10}],statuses:[{id:'active',name:'В процессе'},{id:'done',name:'Завершён'},{id:'frozen',name:'Заморожен'},{id:'new',name:'Запись'}],departments:[{id:'d',name:'Проектный отдел'},{id:'b',name:'Строительный отдел'}],company_info:[{id:'company',name:'ARHITTEK',company_name:'ARHITTEK'}]};
const clone=x=>JSON.parse(JSON.stringify(x));
function query(table){let op='select',val,filters=[],single=false,limit=Infinity;
const q={select(){return q},insert(v){op='insert';val=clone(v);return q},upsert(v){return q.insert(v)},update(v){op='update';val=clone(v);return q},delete(){op='delete';return q},eq(k,v){filters.push(r=>r[k]===v);return q},is(k,v){filters.push(r=>v===null?r[k]==null:r[k]===v);return q},not(k){filters.push(r=>r[k]!=null);return q},in(k,v){filters.push(r=>v.includes(r[k]));return q},order(){return q},limit(n){limit=n;return q},single(){single=true;return q},maybeSingle(){single=true;return q},then(resolve,reject){return Promise.resolve().then(()=>{if(__fail?.table===table&&(!__fail.op||__fail.op===op))return {data:null,error:{message:'Simulated database failure'}};const rows=__db[table]||=[];let matches=rows.filter(r=>filters.every(f=>f(r)));if(op!=='select')__writes.push({table,op,val});if(op==='insert'){matches=(Array.isArray(val)?val:[val]).map(v=>({id:crypto.randomUUID(),created_at:new Date().toISOString(),...v}));rows.push(...matches)}if(op==='update')matches.forEach(r=>Object.assign(r,val));if(op==='delete')__db[table]=rows.filter(r=>!matches.includes(r));matches=matches.slice(0,limit);return {data:clone(single?matches[0]||null:matches),error:null}}).then(resolve,reject)}};return q;}
const client={from:query,rpc:async(n,a)=>{__writes.push({rpc:n,args:clone(a)});if(n==='get_tz_form_by_token')return {data:window.__tz||null,error:null};return {data:null,error:null}},channel(){const c={state:'joined',on(){return c},subscribe(){return c}};return c},removeChannel(){},storage:{from(){return {upload:async()=>({data:{path:'test'},error:null}),getPublicUrl:()=>({data:{publicUrl:'https://example.invalid/test.jpg'}}),remove:async()=>({error:null})}}}};
window.supabase={createClient:()=>client};window.confirm=()=>true;window.alert=()=>{};
localStorage.setItem('arhittek_session',JSON.stringify({employeeId:'admin',name:'Мансур',isAdmin:true,token:'test',createdAt:Date.now()}));sessionStorage.setItem('arhittek_frozen_tried','1');sessionStorage.setItem('arhittek_landscape_tried','1');
})();
