const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
process.env.TZ='Europe/Moscow';
const source=fs.readFileSync(require('path').join(__dirname,'../premium.js'),'utf8');
const names=['num','salaryPaymentMonth','salaryPaymentRows','salaryDueDay','officeDueDay','salaryDueDate','officeDueDate','financeLocalDate','todayISO','salaryPaymentState','obligationPeriod','officeExpected','officePaid','officeObligation'];
const code=names.map(name=>{const start=source.indexOf('function '+name+'(');assert(start>=0,name);const end=source.indexOf('\n}',start);assert(end>=0,name);if(source.slice(start,source.indexOf('\n',start)).includes('}'))return source.slice(start,source.indexOf('\n',start));return source.slice(start,end+2)}).join('\n');
const settings=new Map([['finance_salary_due_day','10'],['finance_rent_due_day','5']]);
const context={Date,Number,String,Math,parseInt,state:{ledger:[],companyExpenses:[]},localStorage:{getItem:k=>settings.get(k)??null},LEGACY_PAID_FN:()=>false};vm.createContext(context);vm.runInContext(code,context);
assert.equal(context.salaryDueDate('2026-09'),'2026-10-10');
assert.equal(context.salaryDueDate('2026-12'),'2027-01-10');
assert.equal(context.officeDueDate('2026-10','rent'),'2026-10-05');
context.todayISO=()=> '2026-10-10';
context.state.ledger=[{id:'p1',type:'salary_payment',payee_employee_id:'e',amount:20000,description:'[salary:2026-09]',entry_date:'2026-10-05'}];
let s=context.salaryPaymentState('e','2026-09',50000);assert.equal(s.paid,20000);assert.equal(s.remaining,30000);assert.equal(s.overdue,false);
context.todayISO=()=> '2026-10-11';assert.equal(context.salaryPaymentState('e','2026-09',50000).overdue,true);
context.state.ledger.push({id:'p2',type:'salary_payment',payee_employee_id:'e',amount:30000,description:'[salary:2026-09]',entry_date:'2026-10-11'});
s=context.salaryPaymentState('e','2026-09',50000);assert.equal(s.remaining,0);assert.equal(s.overdue,false);
context.state.companyExpenses=[{category:'Аренда',amount:40000,expense_date:'2026-10-05',description:'Оплата аренды · период 2026-09'}];
let r=context.officeObligation('rent','2026-09');assert.equal(r.paid,40000);assert.equal(r.remaining,70000);assert.equal(r.overdue,true);assert.equal(context.officePaid('rent','2026-10'),0);
context.state.companyExpenses.push({category:'Аренда',amount:70000,expense_date:'2026-10-11',description:'Оплата аренды · период 2026-09'});
r=context.officeObligation('rent','2026-09');assert.equal(r.remaining,0);assert.equal(r.overdue,false);
console.log('PASS: Moscow deadlines, year rollover, partial salary, overdue boundary, final salary payment, rent period and final rent payment');
